"""Constantes partagées entre parsers, pipeline et API."""

# Mapping pays texte OFAC → ISO-2
COUNTRY_TO_ISO2 = {
    "China": "CN", "Russia": "RU", "Iran": "IR", "Syria": "SY",
    "North Korea": "KP", "Cuba": "CU", "Venezuela": "VE", "Belarus": "BY",
    "Ukraine": "UA", "Myanmar": "MM", "Sudan": "SD", "Somalia": "SO",
    "Libya": "LY", "Iraq": "IQ", "Afghanistan": "AF", "Zimbabwe": "ZW",
    "Burundi": "BI", "Mali": "ML", "Haiti": "HT", "Yemen": "YE",
    "Nicaragua": "NI", "Ethiopia": "ET", "Lebanon": "LB", "Pakistan": "PK",
    "Saudi Arabia": "SA", "UAE": "AE", "Turkey": "TR", "India": "IN",
    "Hong Kong": "CN", "Taiwan": "TW", "Serbia": "RS", "Kosovo": "XK",
    "Georgia": "GE", "Azerbaijan": "AZ", "Uzbekistan": "UZ",
    "Kazakhstan": "KZ", "Kyrgyzstan": "KG", "Tajikistan": "TJ",
    "Turkmenistan": "TM", "Armenia": "AM", "Moldova": "MD",
    "United Arab Emirates": "AE", "United Kingdom": "GB",
    "United States": "US", "Germany": "DE", "France": "FR",
    "Italy": "IT", "Spain": "ES", "Netherlands": "NL", "Belgium": "BE",
    "Switzerland": "CH", "Austria": "AT", "Poland": "PL",
    "Czech Republic": "CZ", "Hungary": "HU", "Romania": "RO",
    "Bulgaria": "BG", "Greece": "GR", "Portugal": "PT",
    "Sweden": "SE", "Norway": "NO", "Denmark": "DK", "Finland": "FI",
    "Japan": "JP", "South Korea": "KR", "Australia": "AU",
    "Canada": "CA", "Mexico": "MX", "Brazil": "BR", "Argentina": "AR",
    "Colombia": "CO", "Peru": "PE", "Chile": "CL", "Ecuador": "EC",
    "Bolivia": "BO", "Paraguay": "PY", "Uruguay": "UY",
    "Nigeria": "NG", "South Africa": "ZA", "Kenya": "KE",
    "Ghana": "GH", "Egypt": "EG", "Morocco": "MA", "Tunisia": "TN",
    "Algeria": "DZ", "Angola": "AO", "Mozambique": "MZ",
    "Tanzania": "TZ", "Uganda": "UG", "Rwanda": "RW",
    "Cameroon": "CM", "Ivory Coast": "CI", "Senegal": "SN",
    "Guinea": "GN", "Congo": "CG", "DR Congo": "CD",
    "Central African Republic": "CF", "Chad": "TD", "Niger": "NE",
    "Burkina Faso": "BF", "Togo": "TG", "Benin": "BJ",
    "Liberia": "LR", "Sierra Leone": "SL", "Guinea-Bissau": "GW",
    "Gambia": "GM", "Mauritania": "MR", "Cape Verde": "CV",
    "Djibouti": "DJ", "Eritrea": "ER", "South Sudan": "SS",
    "Zambia": "ZM", "Malawi": "MW", "Botswana": "BW",
    "Namibia": "NA", "Lesotho": "LS", "Swaziland": "SZ",
    "Comoros": "KM", "Madagascar": "MG", "Mauritius": "MU",
    "Seychelles": "SC", "Indonesia": "ID", "Malaysia": "MY",
    "Thailand": "TH", "Vietnam": "VN", "Philippines": "PH",
    "Singapore": "SG", "Cambodia": "KH", "Laos": "LA",
    "Bangladesh": "BD", "Sri Lanka": "LK", "Nepal": "NP",
    "Maldives": "MV", "Bhutan": "BT", "Jordan": "JO",
    "Israel": "IL", "Palestine": "PS", "Kuwait": "KW",
    "Qatar": "QA", "Bahrain": "BH", "Oman": "OM", "Cyprus": "CY",
    "Malta": "MT",
}
